//! Offline Sudoku puzzle generation and solving.
//!
//! Everything here is pure computation with no I/O and no network access.
//! Puzzles are generated by producing a random complete grid and then
//! digging holes while the solution stays unique.

use rand::Rng;
use rand::seq::SliceRandom;

pub const N: usize = 9;
pub const CELLS: usize = 81;

#[inline]
pub fn idx(row: usize, col: usize) -> usize {
    row * N + col
}

#[inline]
pub fn row_of(i: usize) -> usize {
    i / N
}

#[inline]
pub fn col_of(i: usize) -> usize {
    i % N
}

#[inline]
pub fn box_of(row: usize, col: usize) -> usize {
    (row / 3) * 3 + col / 3
}

/// Five difficulty levels, ordered easy -> zen.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Difficulty {
    Easy,
    Medium,
    Hard,
    Expert,
    Zen,
}

impl Difficulty {
    pub fn all() -> [Difficulty; 5] {
        [
            Difficulty::Easy,
            Difficulty::Medium,
            Difficulty::Hard,
            Difficulty::Expert,
            Difficulty::Zen,
        ]
    }

    /// Number of cells to remove from a complete grid.
    pub fn holes(self) -> usize {
        match self {
            Difficulty::Easy => 36,
            Difficulty::Medium => 44,
            Difficulty::Hard => 50,
            Difficulty::Expert => 55,
            Difficulty::Zen => 60,
        }
    }

    pub fn givens(self) -> usize {
        CELLS - self.holes()
    }

    pub fn name(self) -> &'static str {
        match self {
            Difficulty::Easy => "Easy",
            Difficulty::Medium => "Medium",
            Difficulty::Hard => "Hard",
            Difficulty::Expert => "Expert",
            Difficulty::Zen => "Zen",
        }
    }

    pub fn blurb(self) -> &'static str {
        match self {
            Difficulty::Easy => "Relaxed warm-up, ~45 givens",
            Difficulty::Medium => "Balanced challenge, ~37 givens",
            Difficulty::Hard => "Tough, needs notes, ~31 givens",
            Difficulty::Expert => "Sparse & mean, ~26 givens",
            Difficulty::Zen => "Barely there, ~21 givens",
        }
    }

    pub fn from_index(i: usize) -> Difficulty {
        Self::all()[i % Self::all().len()]
    }

    pub fn index(self) -> usize {
        match self {
            Difficulty::Easy => 0,
            Difficulty::Medium => 1,
            Difficulty::Hard => 2,
            Difficulty::Expert => 3,
            Difficulty::Zen => 4,
        }
    }
}

/// Bitmask of candidates (bits 1..=9) for a cell given the current board.
fn candidates_mask(board: &[u8; CELLS], i: usize) -> u16 {
    let r = row_of(i);
    let c = col_of(i);
    let mut used: u16 = 0;
    for k in 0..N {
        let v = board[idx(r, k)];
        if v != 0 {
            used |= 1 << v;
        }
        let v = board[idx(k, c)];
        if v != 0 {
            used |= 1 << v;
        }
    }
    let br = (r / 3) * 3;
    let bc = (c / 3) * 3;
    for dr in 0..3 {
        for dc in 0..3 {
            let v = board[idx(br + dr, bc + dc)];
            if v != 0 {
                used |= 1 << v;
            }
        }
    }
    (!used) & 0x3FE // keep bits 1..=9
}

/// Count solutions up to `limit` using MRV backtracking. Fast enough for
/// uniqueness checks during generation.
pub fn count_solutions(board: &mut [u8; CELLS], limit: u32) -> u32 {
    // Find the empty cell with fewest candidates.
    let mut best: Option<(usize, u16, u32)> = None;
    for i in 0..CELLS {
        if board[i] == 0 {
            let mask = candidates_mask(board, i);
            let n = mask.count_ones();
            if n == 0 {
                return 0;
            }
            match best {
                None => best = Some((i, mask, n)),
                Some((_, _, bn)) if n < bn => best = Some((i, mask, n)),
                _ => {}
            }
            if best.map(|b| b.2) == Some(1) {
                break;
            }
        }
    }
    let Some((cell, mask, _)) = best else {
        return 1; // no empties: one solution found
    };
    let mut count = 0;
    for v in 1..=9u8 {
        if mask & (1 << v) != 0 {
            board[cell] = v;
            count += count_solutions(board, limit.saturating_sub(count));
            board[cell] = 0;
            if count >= limit {
                return count;
            }
        }
    }
    count
}

/// Solve the puzzle, returning the first solution found (if any).
pub fn solve_one(board: &[u8; CELLS]) -> Option<[u8; CELLS]> {
    let mut b = *board;
    solve_into(&mut b).then_some(b)
}

fn solve_into(board: &mut [u8; CELLS]) -> bool {
    let mut best: Option<(usize, u16, u32)> = None;
    for i in 0..CELLS {
        if board[i] == 0 {
            let mask = candidates_mask(board, i);
            let n = mask.count_ones();
            if n == 0 {
                return false;
            }
            match best {
                None => best = Some((i, mask, n)),
                Some((_, _, bn)) if n < bn => best = Some((i, mask, n)),
                _ => {}
            }
            if best.map(|b| b.2) == Some(1) {
                break;
            }
        }
    }
    let Some((cell, mask, _)) = best else {
        return true;
    };
    for v in 1..=9u8 {
        if mask & (1 << v) != 0 {
            board[cell] = v;
            if solve_into(board) {
                return true;
            }
            board[cell] = 0;
        }
    }
    false
}

/// Build a random complete grid with shuffled DFS.
pub fn full_solution<R: Rng>(rng: &mut R) -> [u8; CELLS] {
    let mut board = [0u8; CELLS];
    fill_random(&mut board, rng);
    board
}

/// Dig holes out of `solved` while the puzzle keeps a unique solution.
/// Returns `(puzzle, solution)`.
pub fn generate<R: Rng>(difficulty: Difficulty, rng: &mut R) -> ([u8; CELLS], [u8; CELLS]) {
    let solved = full_solution(rng);
    let mut puzzle = solved;
    let target = difficulty.holes();

    // Try a few shuffled passes over the givens so sparse levels still
    // reach their target without looping forever.
    let mut holes = 0;
    for _ in 0..4 {
        if holes >= target {
            break;
        }
        let mut order: Vec<usize> = (0..CELLS).filter(|&i| puzzle[i] != 0).collect();
        order.shuffle(rng);
        let mut progress = false;
        for i in order {
            if holes >= target {
                break;
            }
            let backup = puzzle[i];
            puzzle[i] = 0;
            let mut probe = puzzle;
            if count_solutions(&mut probe, 2) == 1 {
                holes += 1;
                progress = true;
            } else {
                puzzle[i] = backup;
            }
        }
        if !progress {
            break;
        }
    }
    (puzzle, solved)
}

/// True when `a` and `b` share a row, column, or 3x3 box.
pub fn shares_house(a: usize, b: usize) -> bool {
    if a == b {
        return true;
    }
    row_of(a) == row_of(b)
        || col_of(a) == col_of(b)
        || box_of(row_of(a), col_of(a)) == box_of(row_of(b), col_of(b))
}

fn fill_random<R: Rng>(board: &mut [u8; CELLS], rng: &mut R) -> bool {
    // MRV choice for speed.
    let mut best: Option<(usize, Vec<u8>)> = None;
    for i in 0..CELLS {
        if board[i] == 0 {
            let mask = candidates_mask(board, i);
            let n = mask.count_ones();
            if n == 0 {
                return false;
            }
            let mut cands: Vec<u8> = (1..=9u8).filter(|v| mask & (1 << v) != 0).collect();
            match &best {
                None => {
                    cands.shuffle(rng);
                    best = Some((i, cands));
                }
                Some((_, bc)) if (cands.len() as u32) < bc.len() as u32 => {
                    cands.shuffle(rng);
                    best = Some((i, cands));
                }
                _ => {}
            }
        }
    }
    let Some((cell, cands)) = best else {
        return true;
    };
    for v in cands {
        board[cell] = v;
        if fill_random(board, rng) {
            return true;
        }
        board[cell] = 0;
    }
    false
}

#[cfg(test)]
mod tests {
    use super::*;
    use rand::SeedableRng;
    use rand::rngs::StdRng;

    fn valid_solution(b: &[u8; CELLS]) -> bool {
        for r in 0..9 {
            let mut seen = [false; 10];
            for c in 0..9 {
                let v = b[idx(r, c)] as usize;
                if v == 0 || seen[v] {
                    return false;
                }
                seen[v] = true;
            }
        }
        for c in 0..9 {
            let mut seen = [false; 10];
            for r in 0..9 {
                let v = b[idx(r, c)] as usize;
                if v == 0 || seen[v] {
                    return false;
                }
                seen[v] = true;
            }
        }
        for br in 0..3 {
            for bc in 0..3 {
                let mut seen = [false; 10];
                for dr in 0..3 {
                    for dc in 0..3 {
                        let v = b[idx(br * 3 + dr, bc * 3 + dc)] as usize;
                        if v == 0 || seen[v] {
                            return false;
                        }
                        seen[v] = true;
                    }
                }
            }
        }
        true
    }

    #[test]
    fn full_grid_is_valid() {
        let mut rng = StdRng::seed_from_u64(1);
        let solved = full_solution(&mut rng);
        assert!(valid_solution(&solved));
    }

    #[test]
    fn generated_puzzles_are_unique() {
        // Easy + Medium only here; sparser levels are covered by the
        // (slower) generation smoke test below with fewer levels.
        for (level, seed) in [(Difficulty::Easy, 7), (Difficulty::Medium, 8)] {
            let mut rng = StdRng::seed_from_u64(seed);
            let (mut puzzle, solved) = generate(level, &mut rng);
            assert!(valid_solution(&solved));
            assert_eq!(count_solutions(&mut puzzle, 2), 1);
            assert_eq!(solve_one(&puzzle).unwrap(), solved);
        }
    }

    #[test]
    fn zen_has_about_twenty_one_givens() {
        assert_eq!(Difficulty::Zen.holes(), 60);
        assert_eq!(Difficulty::Zen.givens(), 21);
        assert_eq!(Difficulty::Zen.name(), "Zen");
        assert_eq!(Difficulty::Zen.index(), 4);
        assert_eq!(Difficulty::from_index(4), Difficulty::Zen);
        assert_eq!(Difficulty::all().len(), 5);
        for (i, d) in Difficulty::all().iter().enumerate() {
            assert_eq!(d.index(), i);
            assert_eq!(Difficulty::from_index(i), *d);
        }
    }

    #[test]
    fn solver_spots_unsolvable() {
        // Take a solved grid, empty one cell, and block its only digit in
        // its column: the cell has zero candidates, so the solver gives up
        // immediately instead of searching a huge tree.
        let (_, solved) = crate::game::Game::test_board();
        let mut bad = solved;
        bad[idx(8, 8)] = 0; // needs 9 ...
        bad[idx(0, 8)] = 9; // ... but 9 is now used in column 8
        let mut probe = bad;
        assert_eq!(count_solutions(&mut probe, 2), 0);
        assert_eq!(solve_one(&bad), None);
    }
}
